# Generated by Django 4.2.7 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='video',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
