# Generated by Django 4.2.7 on 2026-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_activitylog_video_activitylog_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='processed_video',
            field=models.CharField(default='output/default.mp4', max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='Safe', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='video_name',
            field=models.CharField(default='video.mp4', max_length=255),
        ),
    ]
