# Generated by Django 4.2.7 on 2026-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_activitylog_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_online', models.BooleanField(default=True)),
                ('ai_model_loaded', models.BooleanField(default=True)),
                ('server_online', models.BooleanField(default=True)),
                ('sensitivity', models.CharField(default='Medium', max_length=20)),
                ('allowed_activities', models.TextField(default='Walking,Running,Jogging,Yoga,Sitting')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
    ]
